name: CI Build and Push Docker Image

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: docker build -t ***/rajancd:latest -f /path/to/Dockerfile .


    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/rajancd:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/rajancd:latest
    
